const shared = {
    ownerStatusOptions: [
        { id: "interest received", name: "interest received" },
        { id: "offer received", name: "offer received" },
        { id: "cancelled", name: "cancelled" },
        { id: "buyer must book a visit slot", name: "buyer must book a visit slot" },
        { id: "buyer requested to change pre-signing slots", name: "buyer requested to change pre-signing slots" },
        { id: "buyer requested to change home inventory slots", name: "buyer requested to change home inventory slots" },
        { id: "buyer requested to change final signing slots", name: "buyer requested to change final signing slots" },
        { id: "buyer requested to change slots", name: "buyer requested to change slots" },
        { id: "You changed the slot", name: "You changed the slot" },
        { id: "You changed the pre-signing slot", name: "You changed the pre-signing slot" },
        { id: "you changed the final signing slot", name: "you changed the final signing slot" },
        { id: "Visit booked", name: "Visit booked" },
        { id: "Visit review received", name: "Visit review received" },
        { id: "Application file received", name: "Application file received" },
        { id: "You accepted buyer application", name: "You accepted buyer application" },
        { id: "You opened pre signing date", name: "You opened pre signing date" },
        { id: "You opened home inventory slot", name: "You opened home inventory slot" },
        { id: "You refused the application", name: "You refused the application" },
        { id: "You refused the offer", name: "You refused the offer" },
        { id: "Offer refused by buyer", name: "Offer refused by buyer" },
        { id: "You sent a counter-offer", name: "You sent a counter-offer" },
        { id: "You accepted buyer purchase offer", name: "You accepted buyer purchase offer" },
        { id: "Offer accepted", name: "Offer accepted" },
        { id: "You opened home inventory and signing date", name: "You opened home inventory and signing date" },
        { id: "buyer opened a signing date", name: "buyer opened a signing date" },
        { id: "You booked a contract signing date", name: "You booked a contract signing date" },
        { id: "buyer has book a date for contract signing", name: "buyer has book a date for contract signing" },
        { id: "buyer has book a date for home inventory", name: "buyer has book a date for home inventory" },
        { id: "Rental contract has been signed", name: "Rental contract has been signed" },
        { id: "You opened final sale signing dates", name: "You opened final sale signing dates" },
        { id: "buyer opened final sale signing date", name: "buyer opened final sale signing date" },
        { id: "Renter Assigned", name: "Renter Assigned" },
    ],
    renterStatusOption: [
        { id: "interest sent", name: "interest sent" },
        { id: "offer sent", name: "offer sent" },
        { id: "cancelled", name: "cancelled" },
        { id: "invite user for a visit", name: "invite user for a visit" },
        { id: "request to change the pre-sale slot", name: "request to change the pre-sale slot" },
        { id: "request to change the home inventory slot", name: "request to change the home inventory slot" },
        { id: "request to change the final signing slot", name: "request to change the final signing slot" },
        { id: "request to change the visit slot", name: "request to change the visit slot" },
        { id: "owner changed the slot", name: "owner changed the slot" },
        { id: "owner changed the pre-signing slot", name: "owner changed the pre-signing slot" },
        { id: "owner changed the home inventory slot", name: "owner changed the home inventory slot" },
        { id: "visit accept by user", name: "visit accept by user" },
        { id: "visit hosted", name: "visit hosted" },
        { id: "review submit by user", name: "review submit by user" },
        { id: "application submit by user", name: "application submit by user" },
        { id: "owner accept the application", name: "owner accept the application" },
        { id: "preslot opened by owner", name: "preslot opened by owner" },
        { id: "home inventory opened by owner", name: "home inventory opened by owner" },
        { id: "owner reject the application", name: "owner reject the application" },
        { id: "offer refused by owner", name: "offer refused by owner" },
        { id: "offer refused by user", name: "offer refused by user" },
        { id: "offer submit by owner", name: "offer submit by owner" },
        { id: "offer accept by owner", name: "offer accept by owner" },
        { id: "offer accept by user", name: "offer accept by user" },
        { id: "signing date booked by owner", name: "signing date booked by owner" },
        { id: "preslot booked by user", name: "preslot booked by user" },
        { id: "preslot accept by owner", name: "preslot accept by owner" },
        { id: "preslot accept by user", name: "preslot accept by user" },
        { id: "home inventory accept by user", name: "home inventory accept by user" },
        { id: "contract signed by owner", name: "contract signed by owner" },
        { id: "contract signed by user", name: "contract signed by user" },
        { id: "saleslot booked by owner", name: "saleslot booked by owner" },
        { id: "saleslot booked by user", name: "saleslot booked by user" },
        { id: "renter assigned", name: "renter assigned" },
    ],
    byerStatusOption: [
        { id: "interest sent", name: "interest sent" },
        { id: "offer sent", name: "offer sent" },
        { id: "cancelled", name: "cancelled" },
        { id: "invite user for a visit", name: "invite user for a visit" },
        { id: "request to change the pre-sale slot", name: "request to change the pre-sale slot" },
        { id: "request to change the home inventory slot", name: "request to change the home inventory slot" },
        { id: "request to change the final signing slot", name: "request to change the final signing slot" },
        { id: "request to change the visit slot", name: "request to change the visit slot" },
        { id: "owner changed the slot", name: "owner changed the slot" },
        { id: "owner changed the pre-signing slot", name: "owner changed the pre-signing slot" },
        { id: "owner changed the final signing slot", name: "owner changed the final signing slot" },
        { id: "visit accept by user", name: "visit accept by user" },
        { id: "visit hosted", name: "visit hosted" },
        { id: "review submit by user", name: "review submit by user" },
        { id: "offer refused by owner", name: "offer refused by owner" },
        { id: "offer refused by user", name: "offer refused by user" },
        { id: "offer submit by owner", name: "offer submit by owner" },
        { id: "offer accept by owner", name: "offer accept by owner" },
        { id: "offer accept by user", name: "offer accept by user" },
        { id: "signing date booked by owner", name: "signing date booked by owner" },
        { id: "preslot booked by user", name: "preslot booked by user" },
        { id: "preslot accept by owner", name: "preslot accept by owner" },
        { id: "preslot accept by user", name: "preslot accept by user" },
        { id: "preslot booked by owner", name: "preslot booked by owner" },
        { id: "preslot opened by owner", name: "preslot opened by owner" },
        { id: "contract signed by owner", name: "contract signed by owner" },
        { id: "contract signed by user", name: "contract signed by user" },
        { id: "saleslot booked by owner", name: "saleslot booked by owner" },
        { id: "saleslot booked by user", name: "saleslot booked by user" },
        { id: "saleslot accept by user", name: "saleslot accept by user" },
        { id: "confirmation by owner", name: "confirmation by owner" },
        { id: "confirmation by user", name: "confirmation by user" },
        { id: "buyer requested for document", name: "buyer requested for document" },
        { id: "document send by owner", name: "document send by owner" },
    ],
    uniqueStatusOptions : [
    { id: "interest received", name: "interest received" },
    { id: "offer received", name: "offer received" },
    { id: "cancelled", name: "cancelled" },
    { id: "buyer must book a visit slot", name: "buyer must book a visit slot" },
    { id: "buyer requested to change pre-signing slots", name: "buyer requested to change pre-signing slots" },
    { id: "buyer requested to change home inventory slots", name: "buyer requested to change home inventory slots" },
    { id: "buyer requested to change final signing slots", name: "buyer requested to change final signing slots" },
    { id: "buyer requested to change slots", name: "buyer requested to change slots" },
    { id: "You changed the slot", name: "You changed the slot" },
    { id: "You changed the pre-signing slot", name: "You changed the pre-signing slot" },
    { id: "you changed the final signing slot", name: "you changed the final signing slot" },
    { id: "Visit booked", name: "Visit booked" },
    { id: "Visit review received", name: "Visit review received" },
    { id: "Application file received", name: "Application file received" },
    { id: "You accepted buyer application", name: "You accepted buyer application" },
    { id: "You opened pre signing date", name: "You opened pre signing date" },
    { id: "You opened home inventory slot", name: "You opened home inventory slot" },
    { id: "You refused the application", name: "You refused the application" },
    { id: "You refused the offer", name: "You refused the offer" },
    { id: "Offer refused by buyer", name: "Offer refused by buyer" },
    { id: "You sent a counter-offer", name: "You sent a counter-offer" },
    { id: "You accepted buyer purchase offer", name: "You accepted buyer purchase offer" },
    { id: "Offer accepted", name: "Offer accepted" },
    { id: "You opened home inventory and signing date", name: "You opened home inventory and signing date" },
    { id: "buyer opened a signing date", name: "buyer opened a signing date" },
    { id: "You booked a contract signing date", name: "You booked a contract signing date" },
    { id: "buyer has book a date for contract signing", name: "buyer has book a date for contract signing" },
    { id: "buyer has book a date for home inventory", name: "buyer has book a date for home inventory" },
    { id: "Rental contract has been signed", name: "Rental contract has been signed" },
    { id: "You opened final sale signing dates", name: "You opened final sale signing dates" },
    { id: "buyer opened final sale signing date", name: "buyer opened final sale signing date" },
    { id: "Renter Assigned", name: "Renter Assigned" },
    { id: "interest sent", name: "interest sent" },
    { id: "offer sent", name: "offer sent" },
    { id: "invite user for a visit", name: "invite user for a visit" },
    { id: "request to change the pre-sale slot", name: "request to change the pre-sale slot" },
    { id: "request to change the home inventory slot", name: "request to change the home inventory slot" },
    { id: "request to change the final signing slot", name: "request to change the final signing slot" },
    { id: "request to change the visit slot", name: "request to change the visit slot" },
    { id: "owner changed the slot", name: "owner changed the slot" },
    { id: "owner changed the pre-signing slot", name: "owner changed the pre-signing slot" },
    { id: "owner changed the home inventory slot", name: "owner changed the home inventory slot" },
    { id: "visit accept by user", name: "visit accept by user" },
    { id: "visit hosted", name: "visit hosted" },
    { id: "review submit by user", name: "review submit by user" },
    { id: "application submit by user", name: "application submit by user" },
    { id: "owner accept the application", name: "owner accept the application" },
    { id: "preslot opened by owner", name: "preslot opened by owner" },
    { id: "home inventory opened by owner", name: "home inventory opened by owner" },
    { id: "owner reject the application", name: "owner reject the application" },
    { id: "offer refused by owner", name: "offer refused by owner" },
    { id: "offer refused by user", name: "offer refused by user" },
    { id: "offer submit by owner", name: "offer submit by owner" },
    { id: "offer accept by owner", name: "offer accept by owner" },
    { id: "offer accept by user", name: "offer accept by user" },
    { id: "signing date booked by owner", name: "signing date booked by owner" },
    { id: "preslot booked by user", name: "preslot booked by user" },
    { id: "preslot accept by owner", name: "preslot accept by owner" },
    { id: "preslot accept by user", name: "preslot accept by user" },
    { id: "home inventory accept by user", name: "home inventory accept by user" },
    { id: "contract signed by owner", name: "contract signed by owner" },
    { id: "contract signed by user", name: "contract signed by user" },
    { id: "saleslot booked by owner", name: "saleslot booked by owner" },
    { id: "saleslot booked by user", name: "saleslot booked by user" },
    { id: "saleslot accept by user", name: "saleslot accept by user" },
    { id: "confirmation by owner", name: "confirmation by owner" },
    { id: "confirmation by user", name: "confirmation by user" },
    { id: "buyer requested for document", name: "buyer requested for document" },
    { id: "document send by owner", name: "document send by owner" },
]

}

export default shared