var Mongoose = require("mongoose"),
  Schema = Mongoose.Schema;

/**
 * Structured audit log of every AI → user communication.
 *
 * This is the single source of truth for "what did the AI say, to whom, and why."
 * Written from two places (and nowhere else):
 *   1. aiAgentTriggers.service.js → tryFireOnce   (notification-only path)
 *   2. aiOrchestrator.service.js  → deliverAiMessage (full chat + notification path)
 *
 * Both write via a setImmediate fire-and-forget so this never blocks a request.
 */
module.exports = (mongoose) => {
  var schema = mongoose.Schema(
    {
      /** Recipient user */
      userId: {
        type: Schema.Types.ObjectId,
        ref: "users",
        required: true,
        index: true,
      },

      /** Trigger constant — matches TRIGGER keys in both services */
      triggerKey: {
        type: String,
        required: true,
        index: true,
      },

      /** Property context (null for account-level triggers) */
      propertyId: {
        type: Schema.Types.ObjectId,
        ref: "properties",
        default: null,
        index: true,
      },

      /** Interest/lead context (set when trigger fires from an interest event) */
      interestId: {
        type: Schema.Types.ObjectId,
        ref: "interests",
        default: null,
      },

      /**
       * Free-form reference to a transaction, offer, or contract.
       * e.g. interestTransaction._id.toString() or "offer_accepted"
       */
      transactionRef: {
        type: String,
        default: null,
      },

      /** Primary delivery channel for this log entry */
      channel: {
        type: String,
        enum: ["notification", "chat", "email"],
        default: "notification",
      },

      /** Notification / message title (may be null for chat-only turns) */
      title: {
        type: String,
        default: null,
      },

      /** Full message body — never truncated here (notifications may truncate) */
      body: {
        type: String,
        required: true,
      },

      /**
       * Context snapshot passed to the LLM (or null for static messages).
       * Useful for debugging why a specific message was generated.
       */
      metadata: {
        type: Schema.Types.Mixed,
        default: null,
      },

      /**
       * How the body was generated:
       *   "static"  — hard-coded copy in the service
       *   "openai"  — generated by OpenAI (gpt-4o-mini or configured model)
       *   "yves"    — generated by the YvesRealEstateAI FastAPI service
       */
      source: {
        type: String,
        enum: ["static", "openai", "yves"],
        default: "static",
      },
    },
    { timestamps: true }
  );

  // Fast lookup: "all AI messages sent to user X for trigger Y, newest first"
  schema.index({ userId: 1, triggerKey: 1, createdAt: -1 });
  // Admin / monitoring: scan all recent comms
  schema.index({ createdAt: -1 });

  const AiCommunicationLog = mongoose.model("aiCommunicationLog", schema);
  return AiCommunicationLog;
};
