import { ActionId, Objective, OnboardingActionMeta, Profile } from './onboarding.types';

export const ACTION_CATALOG: Record<ActionId, OnboardingActionMeta> = {
  put_property_for_sale: {
    id: 'put_property_for_sale',
    label: 'Mettre votre bien en vente',
    description: "Publiez votre bien pour être contacté par des acheteurs potentiels et bénéficier de l'outil transactionnel.",
    ctaLabel: 'Vendre mon bien',
    targetRoute: '/property1',
    isAvailable: true,
    isActivationGoal: true,
    eventType: 'property_published_sale',
  },
  put_property_for_rent: {
    id: 'put_property_for_rent',
    label: 'Mettre votre bien en location',
    description: "Publiez votre bien pour être contacté par des locataires potentiels et bénéficier de l'outil transactionnel.",
    ctaLabel: 'Louer mon bien',
    targetRoute: '/property1',
    isAvailable: true,
    isActivationGoal: true,
    eventType: 'property_published_rent',
  },
  publish_property_directory: {
    id: 'publish_property_directory',
    label: "Publiez votre bien dans l'annuaire",
    description: "En publiant anonymement votre bien sur l'annuaire AnyHomes, vous recevrez régulièrement des sollicitations spontanées.",
    ctaLabel: 'Référencer mon bien',
    targetRoute: '/property1',
    isAvailable: true,
    isActivationGoal: true,
    eventType: 'property_published_directory',
  },
  estimate_property_value: {
    id: 'estimate_property_value',
    label: 'Tester la valeur de votre bien',
    description: "Avec le Peer-To-Peer estimation, les retours des membres de la communauté vous indiquent à combien ils valorisent votre bien et pourquoi.",
    ctaLabel: 'Estimer mon bien',
    targetRoute: '/social-estimation',
    isAvailable: true,
    eventType: 'p2p_campaign_started',
  },
  consult_transaction_history: {
    id: 'consult_transaction_history',
    label: "Consulter l'historique des transactions",
    description: 'Consultez les transactions passées dans le secteur pour avoir une idée de la valeur de votre bien.',
    ctaLabel: 'Voir les transactions',
    targetRoute: '/past-transactions',
    isAvailable: true,
    eventType: 'transaction_history_searched',
  },
  get_targeted_help: {
    id: 'get_targeted_help',
    label: 'Obtenir une aide ponctuelle et ciblée',
    description: "Faites-vous accompagner par un professionnel de l'immobilier sans commission pour sécuriser votre projet.",
    ctaLabel: 'Parcourir les services',
    targetRoute: '#',
    isAvailable: false,
  },
  learn_real_estate: {
    id: 'learn_real_estate',
    label: "Formez-vous à l'immobilier",
    description: 'Consultez le Learning center pour découvrir nos conseils et bonnes pratiques pour mener votre projet immobilier seul.',
    ctaLabel: 'Learning center',
    targetRoute: '/training',
    isAvailable: true,
    eventType: 'training_content_viewed',
  },
  build_seller_dossier: {
    id: 'build_seller_dossier',
    label: 'Constituer dossier vendeur',
    description: 'Anticipez votre vente en constituant les éléments de votre dossier vendeur pour sécuriser votre vente.',
    ctaLabel: 'Mon dossier vendeur',
    targetRoute: '/seller-file',
    isAvailable: true,
    eventType: 'seller_dossier_document_added',
  },
  build_buyer_dossier: {
    id: 'build_buyer_dossier',
    label: 'Constituer dossier acheteur',
    description: 'Anticipez votre achat en constituant les éléments de votre dossier acheteur pour sécuriser votre projet.',
    ctaLabel: 'Mon dossier acheteur',
    targetRoute: '/buyer-file',
    isAvailable: true,
    eventType: 'buyer_dossier_document_added',
  },
  build_tenant_dossier: {
    id: 'build_tenant_dossier',
    label: 'Constituer dossier locataire',
    description: 'Préparez votre location en constituant les éléments de votre dossier locataire.',
    ctaLabel: 'Mon dossier locataire',
    targetRoute: '/renter-file',
    isAvailable: true,
    eventType: 'tenant_dossier_document_added',
  },
  get_personalized_advice: {
    id: 'get_personalized_advice',
    label: 'Obtenir des conseils personnalisés',
    description: "À chaque étape de votre projet, votre coach immobilier IA vous apporte des réponses et conseils personnalisés 24h/7.",
    ctaLabel: 'Mon coach immo IA',
    targetRoute: '#',
    isAvailable: false,
  },
  peer_estimation: {
    id: 'peer_estimation',
    label: 'Estimez des biens immobiliers',
    description: "Donnez votre estimation de la valeur des biens référencés par les membres de la communauté (Peer-To-Peer estimation).",
    ctaLabel: 'P2P Estimation',
    targetRoute: '/estimation',
    isAvailable: true,
    eventType: 'peer_estimation_submitted',
  },
  search_property_buy: {
    id: 'search_property_buy',
    label: 'Rechercher un bien à acheter',
    description: "Parcourez la liste des biens immobiliers en vente dans l'annuaire pour trouver votre futur bien immobilier.",
    ctaLabel: 'Rechercher',
    targetRoute: '/properties',
    isAvailable: true,
    isActivationGoal: true,
    eventType: 'property_searched_sale',
  },
  search_property_rent: {
    id: 'search_property_rent',
    label: 'Rechercher un bien à louer',
    description: "Parcourez la liste des biens à louer dans l'annuaire pour trouver votre futur logement.",
    ctaLabel: 'Rechercher',
    targetRoute: '/properties',
    isAvailable: true,
    isActivationGoal: true,
    eventType: 'property_searched_rent',
  },
  find_professional: {
    id: 'find_professional',
    label: 'Trouver un professionnel',
    description: "Faites-vous accompagner par un professionnel pour sécuriser votre achat ou votre location immobilière.",
    ctaLabel: 'Trouver un Pro',
    targetRoute: '/prolist',
    isAvailable: true,
    eventType: 'professional_searched',
  },
  browse_property_directory: {
    id: 'browse_property_directory',
    label: "Parcourir l'annuaire des biens immobiliers",
    description: "L'annuaire vous permet de trouver le bien que vous achetez ou louerez dans plusieurs mois ou années.",
    ctaLabel: "Parcourir l'annuaire",
    targetRoute: '/properties?propertyType=directory',
    isAvailable: true,
    isActivationGoal: true,
    eventType: 'directory_browsed',
  },
  follow_property: {
    id: 'follow_property',
    label: 'Suivre un bien immobilier',
    description: "Trouvez un bien dans l'annuaire et suivez son évolution pour ne pas manquer l'opportunité.",
    ctaLabel: 'Rechercher des biens',
    targetRoute: '/properties',
    isAvailable: true,
    eventType: 'property_followed',
  },
  contact_owner_agency: {
    id: 'contact_owner_agency',
    label: "Contacter un propriétaire ou une agence",
    description: "Depuis la fiche d'un bien, initiez une conversation avec un propriétaire ou une agence.",
    ctaLabel: 'Trouver un bien',
    targetRoute: '/properties',
    isAvailable: true,
    eventType: 'owner_contacted',
  },
};

type ConfigKey = `${Profile}_${Objective}`;

export const CONFIGURATION_MATRIX: Partial<Record<ConfigKey, ActionId[]>> = {
  owner_sell: [
    'put_property_for_sale',
    'estimate_property_value',
    'consult_transaction_history',
    'get_targeted_help',
    'learn_real_estate',
    'build_seller_dossier',
    'get_personalized_advice',
    'peer_estimation',
  ],
  owner_rent: [
    'put_property_for_rent',
    'estimate_property_value',
    'get_targeted_help',
    'learn_real_estate',
    'get_personalized_advice',
    'peer_estimation',
  ],
  owner_increase_value: [
    'publish_property_directory',
    'estimate_property_value',
    'learn_real_estate',
    'get_personalized_advice',
    'peer_estimation',
  ],
  searcher_active_buy: [
    'search_property_buy',
    'get_targeted_help',
    'learn_real_estate',
    'build_buyer_dossier',
    'get_personalized_advice',
    'peer_estimation',
    'find_professional',
  ],
  searcher_active_rent: [
    'search_property_rent',
    'get_targeted_help',
    'learn_real_estate',
    'build_tenant_dossier',
    'get_personalized_advice',
    'peer_estimation',
    'find_professional',
  ],
  searcher_passive: [
    'browse_property_directory',
    'publish_property_directory',
    'learn_real_estate',
    'get_personalized_advice',
    'peer_estimation',
    'follow_property',
    'contact_owner_agency',
  ],
};

export function getActionsForConfig(profile: Profile, objective: Objective): OnboardingActionMeta[] {
  const key = `${profile}_${objective}` as ConfigKey;
  const ids = CONFIGURATION_MATRIX[key] ?? [];
  return ids.map((id) => ACTION_CATALOG[id]);
}
